plugin.yml
src/com/github/unchama/seichiassist/SeichiAssist.java
src/com/github/unchama/seichiassist/breakeffect/BlizzardTaskRunnable.java
src/com/github/unchama/seichiassist/breakeffect/ExplosionTaskRunnable.java
src/com/github/unchama/seichiassist/breakeffect/MagicTaskRunnable.java
src/com/github/unchama/seichiassist/breakeffect/MeteoTaskRunnable.java
src/com/github/unchama/seichiassist/breakeffect/VladmiaTaskRunnable.java
src/com/github/unchama/seichiassist/commands/effectCommand.java
src/com/github/unchama/seichiassist/data/BreakArea.java
src/com/github/unchama/seichiassist/data/MenuInventoryData.java
src/com/github/unchama/seichiassist/listener/EntityListener.java
src/com/github/unchama/seichiassist/listener/GachaItemListener.java
src/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.java
src/com/github/unchama/seichiassist/task/AreaControlTaskRunnable.java
src/com/github/unchama/seichiassist/task/AssaultTaskRunnable.java
src/com/github/unchama/seichiassist/task/MultiBreakTaskRunnable.java
src/com/github/unchama/seichiassist/util/BreakUtil.java
src/com/github/unchama/seichiassist/util/Util.java

シルバーフィッシュ石をシルクで壊した時に石がドロップするように修正
マナ完全回復を色有で書けるように修正

ver0.6.7b 

---

.gitignore
config.yml
src/com/github/unchama/seichiassist/Sql.java
src/com/github/unchama/seichiassist/data/MenuInventoryData.java
src/com/github/unchama/seichiassist/data/MineStack.java
src/com/github/unchama/seichiassist/listener/PlayerInventoryListener.java
src/com/github/unchama/seichiassist/listener/PlayerPickupItemListener.java
src/com/github/unchama/seichiassist/task/LoadPlayerDataTaskRunnable.java
src/com/github/unchama/seichiassist/task/PlayerDataSaveTaskRunnable.java

Minestack対応ブロック追加

---

src/com/github/unchama/seichiassist/Sql.java
src/com/github/unchama/seichiassist/data/MenuInventoryData.java
src/com/github/unchama/seichiassist/data/MineStack.java
src/com/github/unchama/seichiassist/listener/PlayerInventoryListener.java
src/com/github/unchama/seichiassist/listener/PlayerPickupItemListener.java
src/com/github/unchama/seichiassist/task/LoadPlayerDataTaskRunnable.java
src/com/github/unchama/seichiassist/task/PlayerDataSaveTaskRunnable.java
src/com/github/unchama/seichiassist/util/BreakUtil.java

MineStackサブID対応・ブロック追加

---

src/com/github/unchama/seichiassist/data/MenuInventoryData.java
src/com/github/unchama/seichiassist/listener/EntityListener.java
src/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.java
src/com/github/unchama/seichiassist/task/AssaultTaskRunnable.java
src/com/github/unchama/seichiassist/task/MultiBreakTaskRunnable.java

・複数種類同時破壊スキルの説明を追加
・破壊スキルの処理順を一部変更(アサルトのみ修正、その他のスキルは未完成)
・遠距離スキルで複数種類一括破壊ができるように修正

説明文を追加、アサルト・遠距離破壊スキル修正

---

src/com/github/unchama/seichiassist/MineStackObj.java
src/com/github/unchama/seichiassist/SeichiAssist.java
src/com/github/unchama/seichiassist/Sql.java
src/com/github/unchama/seichiassist/data/MenuInventoryData.java
src/com/github/unchama/seichiassist/data/MineStack.java
src/com/github/unchama/seichiassist/data/PlayerData.java
src/com/github/unchama/seichiassist/listener/PlayerInventoryListener.java
src/com/github/unchama/seichiassist/listener/PlayerPickupItemListener.java
src/com/github/unchama/seichiassist/task/LoadPlayerDataTaskRunnable.java
src/com/github/unchama/seichiassist/task/PlayerDataSaveTaskRunnable.java
src/com/github/unchama/seichiassist/util/BreakUtil.java

SeichiAssistクラスのminestacklistに追加するだけでMineStackのアイテム・ブロック追加ができるように変更(ガチャアイテム未対応)

MineStackクラス構造変更

---

src/com/github/unchama/seichiassist/data/MenuInventoryData.java
src/com/github/unchama/seichiassist/data/MineStackGachaData.java
src/com/github/unchama/seichiassist/listener/PlayerInventoryListener.java

MineStack格納処理を変更

---

plugin.yml
src/com/github/unchama/seichiassist/SeichiAssist.java
src/com/github/unchama/seichiassist/Sql.java
src/com/github/unchama/seichiassist/commands/rmpCommand.java

必要パーミッション：multiseichiplugin.rmp
/rmp <日数>の実行により、<日数>以上ログインしていないOwnerのみで構成されたRegionを表示する。
rmpCommand.java#72のコメント解除により、該当Regionのremoveも可能。

/rmpコマンドの追加

---

src/com/github/unchama/seichiassist/commands/rmpCommand.java

/rmp [<日数> [<削除フラグ: true/false>]]
・日数のデフォルトを7日に設定
・削除フラグtrueで整地ワールドに限りremoveを実施(要/rg remove permission)

/rmp 削除機能追加

---

src/com/github/unchama/seichiassist/Sql.java
src/com/github/unchama/seichiassist/data/ExpBar.java
src/com/github/unchama/seichiassist/data/Mana.java
src/com/github/unchama/seichiassist/data/MenuInventoryData.java
src/com/github/unchama/seichiassist/data/PlayerData.java
src/com/github/unchama/seichiassist/listener/PlayerInventoryListener.java
src/com/github/unchama/seichiassist/task/LoadPlayerDataTaskRunnable.java
src/com/github/unchama/seichiassist/task/PlayerDataSaveTaskRunnable.java

default 非表示、木の棒の先頭プレイヤーアイコンにトグル割り振り
[デバッグ]debugmodeのみデバッグ可能、非debugmodeのみトグル可能

ExpBar機能の追加

---

src/com/github/unchama/seichiassist/SeichiAssist.java
src/com/github/unchama/seichiassist/data/MenuInventoryData.java
src/com/github/unchama/seichiassist/listener/PlayerInventoryListener.java

MineStackアプデ

---

src/com/github/unchama/seichiassist/listener/PlayerClickListener.java

RIGHT_CLICK_AIRの際に消費されない不具合を修正

EXP瓶一括使用不具合修正

---

src/com/github/unchama/seichiassist/SeichiAssist.java
src/com/github/unchama/seichiassist/breakeffect/MagicTaskRunnable.java
src/com/github/unchama/seichiassist/data/ActiveSkillData.java
src/com/github/unchama/seichiassist/listener/PlayerJoinListener.java
src/com/github/unchama/seichiassist/listener/PlayerMoveListener.java
src/com/github/unchama/seichiassist/task/ManaRegeneTaskRunnable.java

・マナ自然回復
無動作5秒ごとに1%回復設定。
無効化：SeichiAssist.javaのリスナー登録を解除
getServer().getPluginManager().registerEvents(new PlayerMoveListener(),
this);
・アサルト自動off
整地ワールドから出た後にアサルトスキルをoffされるよう変更。
無効化：PlayerJoinListener.javaの「// アサルトスキルを切る」部分のコメントアウト
・co i自動off
整地ワールドから出た後にco iをoffされるよう変更。
無効化：PlayerJoinListener.javaの「// coreprotectを切る」部分のコメントアウト
・Magic色追加
プレミアムエフェクトMagicを、1色から4色に追加。
無効化：MagicTaskRunnable.java
red.setColor(colors[rd]);　→　red.setColor(colors[0]);

マナ自然回復／アサルト自動off／co i自動off／Magic色追加

---

src/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.java

レベルを満たしている場合、整地ワールドにいる時は常時ONとなるよう変更

複数種類破壊パッシブ変更

---

plugin.yml
src/com/github/unchama/seichiassist/SeichiAssist.java
src/com/github/unchama/seichiassist/Sql.java
src/com/github/unchama/seichiassist/commands/mebiusCommand.java
src/com/github/unchama/seichiassist/data/PlayerData.java
src/com/github/unchama/seichiassist/listener/MebiusListener.java
src/com/github/unchama/seichiassist/task/HalfHourTaskRunnable.java
src/com/github/unchama/seichiassist/task/MebiusTaskRunnable.java

無効化：下記3点コメントアウト
Sql.java：MebiusListener.give(p);
SeichiAssist.java：getServer().getPluginManager().registerEvents(new MebiusListener(), this);
PlayerData.java：this.mebius = new MebiusTaskRunnable(this);

Tipsヘルメット Mebius実装

---

src/com/github/unchama/seichiassist/breakeffect/MagicTaskRunnable.java

・ポップする鳥を1羽に減少
・duplicatedのEffect.NOTEをParticle.NOTEに変更

Magicタスク軽減

---

src/com/github/unchama/seichiassist/listener/MebiusListener.java

→水中呼吸を限界値以上にすると明るくなりすぎて見えない
…解決したら戻したい

水中呼吸の上限を3に設定

---

src/com/github/unchama/seichiassist/listener/MebiusListener.java
src/com/github/unchama/seichiassist/task/MebiusTaskRunnable.java

MEBIUS台詞追加

---

src/com/github/unchama/seichiassist/Sql.java
src/com/github/unchama/seichiassist/breakeffect/MagicTaskRunnable.java
src/com/github/unchama/seichiassist/commands/effectCommand.java
src/com/github/unchama/seichiassist/commands/mebiusCommand.java
src/com/github/unchama/seichiassist/data/MenuInventoryData.java
src/com/github/unchama/seichiassist/data/PlayerData.java
src/com/github/unchama/seichiassist/listener/MebiusListener.java
src/com/github/unchama/seichiassist/listener/PlayerInventoryListener.java
src/com/github/unchama/seichiassist/task/LoadPlayerDataTaskRunnable.java
src/com/github/unchama/seichiassist/task/MinuteTaskRunnable.java
src/com/github/unchama/seichiassist/task/PlayerDataSaveTaskRunnable.java

・エクスプロージョン+マジックで鳥湧きスギィ！！！対策
プラグインによるエンティティ召喚がされていない状態に限り鳥を召喚するよう変更
…基本的にはMagic召喚の鳥は1羽のみとなる
お好みで鳥の召喚間隔をご調整
MagicTaskRunnable.run
new EntityRemoveTaskRunnable((Entity) e).runTaskLater(plugin, 100);
→100tick(=5sec)間隔
・MEBIUS ANVIL修正
そもそも金床に置けないように変更

マジック鳥減少/MEBIUS ANVIL修正

---

src/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.java
src/com/github/unchama/seichiassist/util/BreakUtil.java

CrossHeartsさんの報告にあったバグの修正対応が完了しました。
手元のマイクラで正しく動作していることは確認しました。
お手数ですがデバッグの方をよろしくお願いいたします

#97 アイテムを直接インベントリに入れる機能バグ修正

---

src/com/github/unchama/seichiassist/SeichiAssist.java

#149 minestackブロック一括クラフトに変換項目追加
#155 ブロックを並べるスキルでMineStackに対応するブロックを増やす

アイディア#149、#155実装

---

src/com/github/unchama/seichiassist/bungee/BungeeReceiver.java
src/com/github/unchama/seichiassist/listener/MebiusListener.java
src/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.java
src/com/github/unchama/seichiassist/listener/PlayerInventoryListener.java
src/com/github/unchama/seichiassist/task/TitleUnlockTaskRunnable.java

・seichiinfoの通知を消去
・mebiusのShift+Click置き無効化
・mebiusのLvupタイミング修正
・バレンタイン用の仕込み2点

バレンタインアップデート

---

src/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.java
src/com/github/unchama/seichiassist/listener/PlayerPickupItemListener.java
src/com/github/unchama/seichiassist/task/MultiBreakTaskRunnable.java
src/com/github/unchama/seichiassist/util/BreakUtil.java

キノコと線路が直接minestackに入らないことがある不具合を修正しました。
また、不評だったインベントリ満タン通知を切りました。

Schwert wurzel

---

src/com/github/unchama/seichiassist/SeichiAssist.java
src/com/github/unchama/seichiassist/Sql.java
src/com/github/unchama/seichiassist/commands/AchieveCommand.java
src/com/github/unchama/seichiassist/commands/effectCommand.java
src/com/github/unchama/seichiassist/commands/gachaCommand.java
src/com/github/unchama/seichiassist/commands/stickCommand.java
src/com/github/unchama/seichiassist/data/MenuInventoryData.java
src/com/github/unchama/seichiassist/listener/EntityListener.java
src/com/github/unchama/seichiassist/listener/GachaItemListener.java
src/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.java
src/com/github/unchama/seichiassist/listener/PlayerInventoryListener.java
src/com/github/unchama/seichiassist/listener/PlayerJoinListener.java
src/com/github/unchama/seichiassist/task/LoadPlayerDataTaskRunnable.java
src/com/github/unchama/seichiassist/task/PlayerDataSaveTaskRunnable.java
src/com/github/unchama/seichiassist/task/PlayerDataUpdateOnJoinRunnable.java

Warning buster

---

src/com/github/unchama/seichiassist/SeichiAssist.java

Gacha stack

---

.gitignore
src/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.java

ハーフ破壊抑制・バグ修正

---

config.yml
src/com/github/unchama/seichiassist/data/MenuInventoryData.java
src/com/github/unchama/seichiassist/data/PlayerData.java
src/com/github/unchama/seichiassist/data/RegionMenuData.java
src/com/github/unchama/seichiassist/listener/RegionInventoryListener.java
src/com/github/unchama/seichiassist/util/Util.java

・プレイヤーの方向検知の部分の修正
・表示面での修正もろもろ

グリッド式保護・レビュー後修正

---

src/com/github/unchama/seichiassist/data/PlayerData.java
src/com/github/unchama/seichiassist/data/RegionMenuData.java
src/com/github/unchama/seichiassist/listener/RegionInventoryListener.java

グリッド式保護バグ修正・機能追加

---

config.yml
src/com/github/unchama/seichiassist/Config.java
src/com/github/unchama/seichiassist/SeichiAssist.java
src/com/github/unchama/seichiassist/Sql.java
src/com/github/unchama/seichiassist/data/PlayerData.java
src/com/github/unchama/seichiassist/listener/newyearevent/NewYearBagListener.java
src/com/github/unchama/seichiassist/listener/newyearevent/NewYearsEvent.java
src/com/github/unchama/seichiassist/listener/newyearevent/README.md
src/com/github/unchama/seichiassist/task/LoadPlayerDataTaskRunnable.java
src/com/github/unchama/seichiassist/task/PlayerDataSaveTaskRunnable.java

運営イベントコーディック

---

config.yml
plugin.yml
src/com/github/unchama/seichiassist/data/GridTemplate.java
src/com/github/unchama/seichiassist/data/PlayerData.java
src/com/github/unchama/seichiassist/data/RegionMenuData.java
src/com/github/unchama/seichiassist/listener/RegionInventoryListener.java
src/com/github/unchama/seichiassist/util/Util.java

・15ブロック=1ユニットとする独自システムを導入
・GUIが見にくくなってしまったため,近日中に改善する。

グリッド式保護・仕様変更

---

src/com/github/unchama/seichiassist/data/EffectData.java

[FIX]`"採掘量から"という表現を"整地量から"という表現に変更
